### ISSUE TITLE
Error on firmware 0.77.1

### ISSUE THREAD

**Issue by Kasiin** [ginkage/FlippAirMouse#10]
Hello,
I've tried three different versions (official firmware 0.77.1 , RM0222-1752-0.77.2-8621389 and unlshd-030) but they all give the same error:
"Preload failed, API version mismatch"
What can I do? thanks.

**Comment by ginkage** [comment]
Simply download the latest build from FlipC (former Fap Factory): https://flipc.org/ginkage/FlippAirMouse :)

**Comment by Kasiin** [comment]
> Simply download the latest build from FlipC (former Fap Factory): https://flipc.org/ginkage/FlippAirMouse :)

Tried, but the screen just flashes for a second and then returns to the app list.

**Comment by ginkage** [comment]
Could you please try looking into the logs? Such behavior may happen if you e.g. don't have the accel/gyro module attached, or if it's not working properly (e.g. wrong/fake chip used).

**Comment by ginkage** [comment]
By logs I mean connect via serial terminal (e.g. Putty) and type "log" there, not to be confused with the "Log" button in qFlipper.

**Comment by Kasiin** [comment]
Looks like its the chip, I may need to build another board and try again.
.
.
.
>: log
Press CTRL+C to stop...
4971126 [I][LoaderSrv] Starting: Applications
4971132 [I][AnimationManager] Unload animation 'Sasquach_CloudG0ku_128x64'
4976714 [I][fap_loader_app] FAP Loader is loading /ext/apps/GPIO/air_mouse.fap
4977036 [I][fap_loader_app] FAP Loader is mapping
4978103 [I][elf] Total size of loaded sections: 47302
4978106 [I][fap_loader_app] Loaded in 1392ms
4978107 [I][fap_loader_app] FAP Loader is starting app
4978122 [I][BMI160] Init BMI160
4978174 [E][BMI160] Device not ready!
4978201 [I][fap_loader_app] FAP app returned: -1

**Comment by Kasiin** [comment]
Finally found the root cause, I was greedy to buy cheap chips, the pads of BMI160 are oxidized can not be tinned, now it works well after slightly polished.

**Comment by ginkage** [comment]
Nice, glad it's resolved then. :)
