### ISSUE TITLE
Null pointer dereference when exiting Bluetooth mode 

### ISSUE THREAD

**Issue by SHMAUS-Carter** [ginkage/FlippAirMouse#11]
I'm running unlshd-055e and your module was included in the extras folder. My hardware module just arrived today and I have noticed that when I press and hold the back button to exit Bluetooth the entire flipper crashes and reboots.
![20230630_123001](https://github.com/ginkage/FlippAirMouse/assets/531233/fe83d0ef-ad81-45fc-862d-d915633742cf)

**Comment by ginkage** [comment]
Thanks, I've reproduced the issue and will look into it.

**Comment by ginkage** [comment]
OK, so this doesn't reproduce on ToT firmware and app build, so likely will be fixed in a future OTA.

**Comment by ginkage** [comment]
Nope, still crashes on 0.86.1... Will try to reproduce again.

**Comment by Idorobots** [comment]
This is also present on OFW 0.88.0.

**Comment by ginkage** [comment]
I think I've just fixed it... Not exactly sure what the issue was, but oh well.
