### ISSUE TITLE
Tracking issues with off-the-shelf BMI160 module

### ISSUE THREAD

**Issue by Idorobots** [ginkage/FlippAirMouse#13]
Hi,

I'm having some issues with tracking using one of those [off-the-shelf purple modules](https://www.chipskey.cc/images/33th/33013.jpg), namely the coursor is all over the place - not only it doesn't track, but also it often jumps between two locations rapidly or swings all the way towards either edge of the screen. It seems that movement does affect it, but it's entirely not controllable.  Calibration doesn't fix the issue either.  I built my adapter board to closely match the position and orientation of the board available in this repository. To avoid any issues stemming from that, but that also didn't help.

Any pointers on how I can try to debug that issue?

I'm running OFW 0.88.0 and I have a dev board debugger.

**Comment by ginkage** [comment]
Weird, that didn't happen before (e.g. on firmware 0.86). I've reproduced it on 0.88, and will look into it.

**Comment by ginkage** [comment]
OK, I still don't know what's going on, but 06b91a0c546de25f6613fa22d2a807bbb658ecd4 fixed it.
It was similarly broken before the first public release, and back then I've fixed it by making `RotationFromVector` method `static inline` (which also doesn't make any sense), but now it broke again, with a similar band-aid non-sensical fix. Oh well...
Debugging that issue did give me a few more gray hairs though...

**Comment by Idorobots** [comment]
I confirm it does work now. Thanks!
