### ISSUE TITLE
Making a MPU6050 version

### ISSUE THREAD

**Issue by AliHj98** [ginkage/FlippAirMouse#15]
Nice work, Im trying to make a gyro gamepad app with the mpu6050 sensor, what was your approach of merging the cardboard sdk with the bmi sensor output?

Thanks

**Comment by ginkage** [comment]
What do you mean, "what was my approach"? The code is right there.

**Comment by eried** [comment]
@AliHj98 did you tried to do the mpu6050 version?

**Comment by ginkage** [comment]
With some recent updates, the app is now even more modular, making it even easier to support new I2C IMUs. Do take a look and feel free to contribute if you decide to create an MPU6050 variant.
