### ISSUE TITLE
Question about schematic and GPIO pins

### ISSUE THREAD

**Issue by averageprogrammer** [ginkage/FlippAirMouse#17]
Hi, great repo with a very full solution. I am very light on the EE knowledge. When I submit the gerber file zip found in the schematic folder I get a preview just like your Original idea picture included in the repo's description. My question is whether the GPIO pins are included and already soldered in the schematic gerber file since it's kind of hard to differentiate from the preview of the gerber file showing a flat top and bottom view with the area of the pin connection showing up as circles. Basically given I ordered your unchanged schematics from JLCPCB will my board come with pins just as shown in the expectation and reality pictures or will I have to buy and solder my own GPIO pins  to the board once it arrives from JLCPCB?

**Comment by ginkage** [comment]
I don't think JLCPCB will pre-solder the header pins, they only do SMD assembly AFAIK.
Luckily, that's the easiest part to solder.

**Comment by averageprogrammer** [comment]
Sounds good! I'll make sure to order a few headers for the orders I made. Thank you for the prompt response and the awesome repo.
