### ISSUE TITLE
Doesn't work via bluetooth on mac

### ISSUE THREAD

**Issue by Max-ctr** [ginkage/FlippAirMouse#18]
Doesn't work via bluetooth on mac, but works via USB
- version 0.9
- Mac OS Monterey 12.7.3
- Flipper oficial firmware 0.98.3

**Comment by ginkage** [comment]
I can't do anything about it: I don't have a Mac to test, and Bluetooth connectivity is provided by firmware, not by the app.

**Comment by bleem313** [comment]
I had the same issue, but it was fixed for me by removing the "Control FlipperName" device from the Mac and then adding it back with the AirMouse app running in Bluetooth mode.
