### ISSUE TITLE
BMI160 alternative?

### ISSUE THREAD

**Issue by fightforge** [ginkage/FlippAirMouse#4]
Hi,
I cannot found BMI160 online, could you suggest a compatible alternative?

Thanks

**Comment by ginkage** [comment]
If you look under `tracking/imu`, you'll find sources for a `LSM6DS3TR-C` driver as well, with some hooks to make it a drop-in replacement. The file `imu.c` shows how to do it pretty easily.

**Comment by fightforge** [comment]
Wow fast reply, ok i will check it.

Thank you so much!
