### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by Noboru-Sam-a** [ginkage/FlippAirMouse#5]
Hey, man, cool stuff.  I have zero experience with this kind of stuff, so I'm finding it a bit difficult to order this thing from JLCPCB.  I put the gerber.zip in and checked that I want the free assembly (I'm assuming that I don't need to change any options thus far).  I then click next, upload the bom and cpl files (chose it as sensor/controller/precision instrument - IR Remote Control), hit next again, but I get something that doesn't look right for the parts:

![Screenshot (16h 27m 21s)](https://user-images.githubusercontent.com/122185675/211175217-af1c12bb-cd52-4dc0-87c8-4e9d422af0dc.jpg)

I'm pretty sure I don't need 5 of the BMI160 or 25 of the 3.9kI thing; I just need one of the BMI and 4 of the 3.9, but I don't know how to change the quantity, or why it generated that many.........oh, I'm guessing that it's because the minimum order is 5 PCBs; but then why is the quantity of the 3.9k 25, and not 4X5=20?

For the 100nF, it came up with nothing even in the search; I tried clicking preorder and found this page:

![Screenshot (16h 39m 46s)](https://user-images.githubusercontent.com/122185675/211175704-56b4b6f0-cd8b-4326-8f5b-1c4c81da5cc9.jpg)

I added 5 to my part cart, but I'm failing to see if it's added to the order.  

The Header didn't even show up, but I found one by searching the Supplier Part No. and added 5 to my part cart, but again I can't see where it went after it says it was added to my part cart.  I'm missing some step for adding these parts to the order, because after I click next, the generated image is missing both the 100nF and Headers only.  

Sorry for being an ignorant noob, but any help would be much appreciated.

**Comment by ginkage** [comment]
The minimum order is indeed 5 PCBs, but for the assembly, the minimum is 2, so you can save some (see "PCBA Qty" option when you start an order).
You can't add header because it will not be soldered anyway, they will only do the SMD components. I guess it's the same story with ordering the parts separately... Try using search, and enter "C14663" there, maybe that would work. Also, try "C23018" for the resistor part, it's cheaper and will give you the right quantity, as it's from the "basic" library.

I've updated the BOM file, so you should be able to use it directly now, with the right components pre-selected.

**Comment by Noboru-Sam-a** [comment]
Just placed my order.  Thanks, man, you're the king.  Oh, for the header I just pop it in and it's good to go like that, right?

**Comment by ginkage** [comment]
It needs to be soldered on, but yeah, simply attach it, and you're set.

**Comment by Noboru-Sam-a** [comment]
Damn, I gotta learn how to solder, now.  Alright, cheers!

**Comment by Noboru-Sam-a** [comment]
Either I failed in four attempts at soldering, or something else went wrong.  Flipper recognizes that I have the module inserted, and I can connect, but the cursor goes all the way to the edge; I can left and right click, but I can't control the cursor, when I wave it around, it just goes all haywire and blinky and to the edges.  In the YouTube vid, I just noticed that there's a black top over the top of the pcb, and a bunch of wires coming from the side, which is different from the picture and what I got.  Any idea of where I'm going wrong?  

Side note: while I was waiting to receive the pcb, I finally got the wiimote and glovepie to work, which is even better, but less compact.

**Comment by Noboru-Sam-a** [comment]
Oh, and the error message I get upon exiting is, "null pointer difference."

**Comment by Noboru-Sam-a** [comment]
*null pointer dereference

**Comment by DogmaBomb** [comment]
i missed how to order the chip and pins when I ordered my PCB :/
does the chip need to be flashed with firmware to make it work? if so how is that done?

**Comment by ginkage** [comment]
> i missed how to order the chip and pins when I ordered my PCB :/ does the chip need to be flashed with firmware to make it work? if so how is that done?

Accel/gyro doesn't need a firmware.

**Comment by ginkage** [comment]
> Either I failed in four attempts at soldering, or something else went wrong. Flipper recognizes that I have the module inserted, and I can connect, but the cursor goes all the way to the edge; I can left and right click, but I can't control the cursor, when I wave it around, it just goes all haywire and blinky and to the edges.

Did you build the .fap file yourself, or downloaded it? Which version of Flipper firmware do you have?

> In the YouTube vid, I just noticed that there's a black top over the top of the pcb, and a bunch of wires coming from the side, which is different from the picture and what I got. Any idea of where I'm going wrong?

That was an early prototype, before I designed my own PCB.

**Comment by DogmaBomb** [comment]
the chip can't be ordered with the PCB right? I need to find it someplace else?
https://www.urbanindustrialproducts.com/products/bmi160?variant=42057074966678&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic

I found this, is this the chip I need?

**Comment by ginkage** [comment]
I've ordered the chip with the PCB, on JLCPCB, and though it was $5 apiece, I was glad to see it was indeed the original one. I've also tested some cheaper knock-offs for $3 together with a PCB and all the other pieces (from eBay; I had to change the Chip ID to make it work), and those fakes were not as good as the original ones.

**Comment by DogmaBomb** [comment]
this is all very new to me, I couldn't figure out how to order the chip with my PCBs, I wound up getting just the PCBs, where is the best place to order just the chip alone?

**Comment by DogmaBomb** [comment]
I need to figure out how to order through JLCPCB correctly with the Gerber file. 
I'm seeing there's more hardware in the photo I need to order as well. Besides the pin, I don't know what these are; the 3 connectors to the left of the chip and the two connectors to the right.

**Comment by ginkage** [comment]
You do need the chip, the four resistors, and the capacitor, and you'd better make sure your soldering skills are up to the task if you want to assemble everything yourself. Although the components I've used aren't the smallest possible, it's still challenging, especially with the chip. I did solder those onto the PCBs with my own hands, but that's just at the limit of my own skill.
This is why there are two extra files available in the repo: BOM (bill of materials) and CPL (component placement list) that you should use when ordering the PCB. To do that, make sure you add "assembly" to your order on JLCPCB, and then everything except for the header pins will arrive pre-soldered for you. You can see what it looks like on the screenshots by topicstarter above.
