### ISSUE TITLE
Flipper Z with airmouse like LG pilot on Android TV

### ISSUE THREAD

**Issue by Marcin84-dev** [ginkage/FlippAirMouse#9]
I cant pair airmouse bt with androidtv but on usb it works fine. Any advices?

**Comment by ginkage** [comment]
Nothing I can do as a part of this project, please file this issue at https://github.com/flipperdevices/flipperzero-firmware

Although, they're likely to tell you it's an issue on the Android TV side, as Flipper is using the standard BLE HID implementation (e.g. your TV may not support BLE, or something).
